In [1]:
import pandas as pd
import requests

In [2]:
pip install requests

Requirement already satisfied: requests in d:\anaconda\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import requests

url = "https://movies-ratings2.p.rapidapi.com/ratings"

querystring = {"id":"tt0111161"}

headers = {
	"x-rapidapi-key": "b35ebbf597mshcd8fed239e5035ap1016f7jsnbc5d586aa885",
	"x-rapidapi-host": "movies-ratings2.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

data=response.json()

In [5]:
import pandas as pd

data = response.json()

df = pd.json_normalize(data)

df

,tmdbId,imdbId,lastUpdated,ratings.imdb.score,ratings.imdb.reviewsCount,ratings.imdb.url,ratings.metacritic.metascore,ratings.metacritic.userScore,ratings.metacritic.averageScore,ratings.metacritic.url,...,media.tagline,media.title,media.video,media.external_ids.imdb_id,media.external_ids.wikidata_id,media.external_ids.facebook_id,media.external_ids.instagram_id,media.external_ids.twitter_id,media.director,media.media_type
0,278,tt0111161,1738173381282,9.3,3000000,https://www.imdb.com/title/tt0111161/,82,9.3,8.8,https://www.metacritic.com/movie/the-shawshank...,...,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,False,tt0111161,Q172241,None,None,None,Frank Darabont,movie

In [6]:
df.head()

,tmdbId,imdbId,lastUpdated,ratings.imdb.score,ratings.imdb.reviewsCount,ratings.imdb.url,ratings.metacritic.metascore,ratings.metacritic.userScore,ratings.metacritic.averageScore,ratings.metacritic.url,...,media.tagline,media.title,media.video,media.external_ids.imdb_id,media.external_ids.wikidata_id,media.external_ids.facebook_id,media.external_ids.instagram_id,media.external_ids.twitter_id,media.director,media.media_type
0,278,tt0111161,1738173381282,9.3,3000000,https://www.imdb.com/title/tt0111161/,82,9.3,8.8,https://www.metacritic.com/movie/the-shawshank...,...,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,False,tt0111161,Q172241,None,None,None,Frank Darabont,movie

In [8]:
import requests
import pandas as pd

url = "https://movies-ratings2.p.rapidapi.com/ratings"

headers = {
    "x-rapidapi-key": "b35ebbf597mshcd8fed239e5035ap1016f7jsnbc5d586aa885",
    "x-rapidapi-host": "movies-ratings2.p.rapidapi.com",
    "Content-Type": "application/json"
}

movie_ids = [
    "tt0111161",  # Shawshank Redemption
    "tt0068646",  # The Godfather
    "tt0468569",  # The Dark Knight
    "tt0109830",  # Forrest Gump
    "tt0133093"   # The Matrix
]

movies = []

for movie_id in movie_ids:
    response = requests.get(
        url,
        headers=headers,
        params={"id": movie_id}
    )

    data = response.json()

    movies.append({
        "IMDb_ID": data.get("imdbId"),
        "TMDB_ID": data.get("tmdbId"),
        "IMDb_Score": data.get("ratings", {})
                           .get("imdb", {})
                           .get("score"),
        "Reviews_Count": data.get("ratings", {})
                              .get("imdb", {})
                              .get("reviewsCount")
    })

df = pd.DataFrame(movies)

df

     IMDb_ID  TMDB_ID  IMDb_Score  Reviews_Count
0  tt0111161      278         9.3        3000000
1  tt0068646      238         9.2        2200000
2  tt0468569      155         9.1        3100000
3  tt0109830       13         8.8        2300000
4  tt0133093      603         8.7        2200000

In [10]:
df.to_csv("movies_dataset.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [11]:
df

     IMDb_ID  TMDB_ID  IMDb_Score  Reviews_Count
0  tt0111161      278         9.3        3000000
1  tt0068646      238         9.2        2200000
2  tt0468569      155         9.1        3100000
3  tt0109830       13         8.8        2300000
4  tt0133093      603         8.7        2200000