**one hot encoding**

one hot encoding is used for the nominal categorical data

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
df=pd.read_csv('Cars Datasets 2025.csv',encoding='latin1')

In [20]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [7]:
df.shape

(1218, 11)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Names              1218 non-null   object
 1   Cars Names                 1218 non-null   object
 2   Engines                    1218 non-null   object
 3   CC/Battery Capacity        1215 non-null   object
 4   HorsePower                 1218 non-null   object
 5   Total Speed                1218 non-null   object
 6   Performance(0 - 100 )KM/H  1212 non-null   object
 7   Cars Prices                1218 non-null   object
 8   Fuel Types                 1218 non-null   object
 9   Seats                      1218 non-null   object
 10  Torque                     1217 non-null   object
dtypes: object(11)
memory usage: 104.8+ KB

In [12]:
df['Company Names'].value_counts()

Company Names
Nissan               149
Volkswagen           109
Porsche               96
Mazda                 87
Mitsubishi            60
GMC                   59
Chevrolet             58
Peugeot               54
Kia                   54
Ford                  54
TOYOTA                45
BMW                   41
Jaguar Land Rover     40
Tata Motors           29
ROLLS ROYCE           29
Acura                 27
LAMBORGHINI           24
HYUNDAI               23
AUDI                  21
MERCEDES              21
Cadillac              20
Jeep                  19
KIA                   16
ASTON MARTIN          11
Bugatti               10
NISSAN                10
Tesla                 10
FERRARI                9
Volvo                  9
HONDA                  7
Toyota                 5
MAHINDRA               3
VOLVO                  3
MARUTI SUZUKI          3
KIA                    1
ROLLS ROYCE            1
BENTLEY                1
Name: count, dtype: int64

In [21]:
df['Fuel Types'].value_counts()

Fuel Types
Petrol                     871
Diesel                     106
Electric                    97
Hybrid                      79
Petrol/Diesel               16
Petrol/Hybrid               16
Plug-in Hybrid               5
Diesel/Petrol                4
Hybrid (Petrol)              4
Hydrogen                     3
Petrol, Diesel               3
Petrol/AWD                   2
Petrol, Hybrid               2
Hybrid (Gas + Electric)      1
plug in hyrbrid              1
Gas / Hybrid                 1
Diesel Hybrid                1
Petrol (Hybrid)              1
Petrol/EV                    1
Hybrid/Petrol                1
CNG/Petrol                   1
Hybrid/Electric              1
Hybrid / Plug-in             1
Name: count, dtype: int64

In [22]:
selected = ['Petrol', 'Diesel', 'Electric','Hybrid']

df = df[df['Fuel Types'].isin(selected)]

In [23]:
df['Fuel Types'].value_counts()

Fuel Types
Petrol      871
Diesel      106
Electric     97
Hybrid       79
Name: count, dtype: int64

**1. One Hot Encoding using pandas**

In [ ]:
pd.get_dummies(df,columns=['Fuel Types'])
#the fuel Types column is converted into 4 columns with 0 and 1 values. 
# This is called one hot encoding.
#each column represents a category and the value is 1 if the row belongs to that category and 0 otherwise.

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Seats,Torque,Fuel Types_Diesel,Fuel Types_Electric,Fuel Types_Hybrid,Fuel Types_Petrol
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",5,900 Nm,False,False,False,True
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",5,100 - 140 Nm,False,False,False,True
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",4,900 Nm,False,False,False,True
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",2,560 Nm,False,False,False,True
5,BMW,Mclaren 720s,V8,"3,994 cc",710 hp,341 km/h,2.9 sec,"$499,000",2,770 Nm,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Mazda,Luce Rotary Coupe,1.3L Wankel Rotary Engine,"1,308 cc",135 hp,175 km/h,12.0 sec,"$25,000 - $30,000",4,180 Nm,False,False,False,True
1211,Mazda,Millenia S,2.5L V6,"2,500 cc",200 hp,220 km/h,8.0 sec,"$30,000 - $35,000",5,250 Nm,False,False,False,True
1212,Mazda,787B (Race Car),2.6L Wankel Rotary Engine,"2,620 cc",700 hp,320 km/h,3.5 sec,"$5,000,000 - $7,000,000",1,500 Nm,False,False,False,True
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"$50,000",7,630 Nm,False,False,True,False
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec," 33,000",5,190  205 Nm,False,False,True,False

**now**, here we will solve multicolinerity, to remove one column from fule tye colum

In [30]:
pd.get_dummies(df, columns=['Fuel Types'], drop_first=True)
# drop_first=True drops the first column to avoid multicollinearity.

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Seats,Torque,Fuel Types_Electric,Fuel Types_Hybrid,Fuel Types_Petrol
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",5,900 Nm,False,False,True
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",5,100 - 140 Nm,False,False,True
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",4,900 Nm,False,False,True
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",2,560 Nm,False,False,True
5,BMW,Mclaren 720s,V8,"3,994 cc",710 hp,341 km/h,2.9 sec,"$499,000",2,770 Nm,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Mazda,Luce Rotary Coupe,1.3L Wankel Rotary Engine,"1,308 cc",135 hp,175 km/h,12.0 sec,"$25,000 - $30,000",4,180 Nm,False,False,True
1211,Mazda,Millenia S,2.5L V6,"2,500 cc",200 hp,220 km/h,8.0 sec,"$30,000 - $35,000",5,250 Nm,False,False,True
1212,Mazda,787B (Race Car),2.6L Wankel Rotary Engine,"2,620 cc",700 hp,320 km/h,3.5 sec,"$5,000,000 - $7,000,000",1,500 Nm,False,False,True
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"$50,000",7,630 Nm,False,True,False
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec," 33,000",5,190  205 Nm,False,True,False

**why we not use this pandas mthod in ML?**

Because the pandas can remeber the previous thing that why we use sklearn classes

In [34]:
df.head(2)

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm

**2. OneHotEncoding using sklearn**

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['Company Names','Fuel Types']],df['Cars Prices'],test_size=0.2,random_state=42)

In [40]:
x_train

          Company Names Fuel Types
450              Nissan     Petrol
101                 BMW     Petrol
169                 BMW     Petrol
1105         Mitsubishi     Petrol
894               Volvo     Diesel
...                 ...        ...
1101         Mitsubishi     Petrol
1154              Mazda     Petrol
1192              Mazda     Petrol
909   Jaguar Land Rover     Petrol
1188              Mazda     Petrol

[922 rows x 2 columns]

In [41]:
from sklearn.preprocessing import OneHotEncoder

In [75]:
ohe=OneHotEncoder(drop='first', sparse_output=False,dtype=np.int32)
#drop='first' drops the first column to avoid multicollinearity.
#sparse=False returns a dense array instead of a sparse matrix.
#dtype=np.int32 returns the array as int32 instead of float64.

on which colum we do encoding we will separate these colum and perform encoding after encoding we will again add with another columns, but htis is hard method. 

we will do this with **column transformer**, this is easy method.

In [76]:
x_train_new=ohe.fit_transform(x_train[['Fuel Types']])

In [77]:
x_test_new=ohe.transform(x_test[['Fuel Types']])

In [78]:
x_train_new

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

now we cut the all the colums from datset except 'Fule Types' and append with 'x_train_new' and 'x_test_new'

In [79]:
np.hstack((x_train[['Company Names']].values,x_train_new))

array([['Nissan', 0, 0, 1],
       ['BMW', 0, 0, 1],
       ['BMW', 0, 0, 1],
       ...,
       ['Mazda', 0, 0, 1],
       ['Jaguar Land Rover', 0, 0, 1],
       ['Mazda', 0, 0, 1]], dtype=object)

In [80]:
np.hstack((x_test[['Company Names']].values,x_test_new))

array([['GMC', 0, 0, 1],
       ['Nissan', 0, 0, 0],
       ['Peugeot', 0, 1, 0],
       ['Tata Motors', 0, 0, 1],
       ['Nissan', 0, 1, 0],
       ['Mitsubishi', 0, 0, 1],
       ['TOYOTA', 1, 0, 0],
       ['Kia', 0, 0, 1],
       ['Volkswagen', 1, 0, 0],
       ['Nissan', 0, 0, 1],
       ['Ford', 0, 0, 0],
       ['Mazda', 0, 0, 1],
       ['Mitsubishi', 0, 0, 0],
       ['Peugeot', 0, 0, 1],
       ['Ford', 0, 0, 0],
       ['Acura', 0, 1, 0],
       ['Nissan', 0, 0, 1],
       ['Volkswagen', 1, 0, 0],
       ['Cadillac', 1, 0, 0],
       ['Volkswagen', 0, 0, 0],
       ['Peugeot', 1, 0, 0],
       ['Tesla', 1, 0, 0],
       ['Volkswagen', 0, 0, 0],
       ['BMW', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['MERCEDES', 0, 0, 1],
       ['Ford', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['ROLLS ROYCE', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Ford', 0, 0, 1],
       ['LAMBORGHINI', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Peugeot', 0, 1, 0],
       ['Jaguar Land Rover', 0, 0, 1],
       ['KIA', 0, 0, 1],
       ['AUDI', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['ROLLS ROYCE', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Volkswagen', 0, 0, 0],
       ['Cadillac', 0, 0, 1],
       ['ROLLS ROYCE', 0, 0, 1],
       ['Acura', 0, 0, 1],
       ['Acura', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Kia', 0, 0, 1],
       ['BMW', 0, 0, 1],
       ['Mitsubishi', 0, 0, 0],
       ['Ford', 0, 1, 0],
       ['Nissan', 0, 1, 0],
       ['LAMBORGHINI', 0, 0, 1],
       ['NISSAN', 0, 0, 1],
       ['LAMBORGHINI', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Kia', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Acura', 0, 0, 1],
       ['Ford', 0, 0, 0],
       ['Peugeot', 0, 0, 0],
       ['GMC', 0, 0, 1],
       ['Peugeot', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['BMW', 0, 0, 1],
       ['Kia', 0, 1, 0],
       ['Jeep', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Volvo', 0, 0, 0],
       ['LAMBORGHINI', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Tata Motors', 0, 0, 0],
       ['Nissan', 0, 0, 1],
       ['Kia', 0, 0, 1],
       ['TOYOTA', 0, 1, 0],
       ['Cadillac', 0, 0, 1],
       ['Tesla', 1, 0, 0],
       ['AUDI', 0, 0, 1],
       ['ROLLS ROYCE', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Mitsubishi', 0, 0, 0],
       ['Tata Motors', 1, 0, 0],
       ['TOYOTA', 0, 0, 1],
       ['Porsche', 1, 0, 0],
       ['Volkswagen', 0, 1, 0],
       ['Peugeot', 0, 0, 1],
       ['Peugeot', 0, 0, 0],
       ['GMC', 0, 0, 1],
       ['Jeep', 0, 1, 0],
       ['Nissan', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['TOYOTA', 1, 0, 0],
       ['Nissan', 0, 0, 1],
       ['MERCEDES', 1, 0, 0],
       ['Porsche', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['ASTON MARTIN', 0, 1, 0],
       ['Peugeot', 0, 0, 1],
       ['Volkswagen', 1, 0, 0],
       ['Volkswagen', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Kia', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Volkswagen', 0, 0, 0],
       ['Nissan', 0, 0, 1],
       ['MERCEDES', 0, 0, 1],
       ['Jeep', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Chevrolet', 0, 0, 1],
       ['Ford', 0, 0, 0],
       ['Nissan', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Volkswagen', 1, 0, 0],
       ['Jaguar Land Rover', 1, 0, 0],
       ['Jaguar Land Rover', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['FERRARI', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Ford', 0, 0, 1],
       ['Chevrolet', 0, 0, 1],
       ['LAMBORGHINI', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Chevrolet', 0, 0, 1],
       ['BMW', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Tata Motors', 0, 0, 0],
       ['GMC', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Chevrolet', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Kia', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Jeep', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Kia', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Acura', 0, 0, 1],
       ['Nissan', 0, 0, 0],
       ['Nissan', 0, 0, 1],
       ['MERCEDES', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Peugeot', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['Ford', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Ford', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['ROLLS ROYCE', 0, 0, 1],
       ['Chevrolet', 0, 0, 1],
       ['AUDI', 1, 0, 0],
       ['GMC', 0, 0, 1],
       ['Cadillac', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['BMW', 0, 1, 0],
       ['Ford', 0, 0, 0],
       ['Nissan', 0, 0, 1],
       ['Volkswagen', 1, 0, 0],
       ['AUDI', 1, 0, 0],
       ['Cadillac', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Tata Motors', 0, 0, 0],
       ['Nissan', 0, 0, 1],
       ['TOYOTA', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['Volkswagen', 0, 0, 0],
       ['LAMBORGHINI', 0, 0, 1],
       ['Nissan', 1, 0, 0],
       ['TOYOTA', 0, 1, 0],
       ['Kia', 0, 0, 1],
       ['Toyota', 0, 1, 0],
       ['Volkswagen', 0, 0, 1],
       ['KIA', 0, 1, 0],
       ['TOYOTA', 0, 0, 1],
       ['HONDA', 0, 0, 1],
       ['MARUTI SUZUKI', 0, 0, 1],
       ['GMC', 1, 0, 0],
       ['Nissan', 0, 0, 1],
       ['Kia', 0, 1, 0],
       ['MERCEDES', 0, 0, 1],
       ['Volkswagen', 1, 0, 0],
       ['Chevrolet', 0, 0, 1],
       ['Porsche', 0, 0, 1],
       ['HYUNDAI', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Acura', 0, 0, 1],
       ['ASTON MARTIN', 0, 0, 1],
       ['NISSAN', 0, 0, 1],
       ['Jaguar Land Rover', 0, 0, 1],
       ['AUDI', 0, 0, 1],
       ['LAMBORGHINI', 0, 0, 1],
       ['Jaguar Land Rover', 0, 0, 1],
       ['Chevrolet', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Acura', 0, 0, 1],
       ['Kia', 0, 1, 0],
       ['Jaguar Land Rover', 0, 0, 1],
       ['AUDI', 0, 0, 1],
       ['Nissan', 0, 0, 1],
       ['Jaguar Land Rover', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['GMC', 0, 0, 1],
       ['Mitsubishi', 0, 0, 1],
       ['Bugatti', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Peugeot', 0, 0, 1],
       ['Volkswagen', 0, 0, 1],
       ['LAMBORGHINI', 0, 0, 1],
       ['Mitsubishi', 0, 0, 1],
       ['Porsche', 0, 1, 0],
       ['Porsche', 0, 0, 1],
       ['LAMBORGHINI', 0, 0, 1],
       ['Mazda', 0, 0, 1],
       ['Acura', 0, 0, 1]], dtype=object)

**3. OneHotEncoding with Top Categories**

In [83]:
counts=df['Company Names'].value_counts()

In [89]:
df['Company Names'].nunique()
threshold=20

In [92]:
#find those companies that have less than 50 cars in the dataset.
repl=counts[counts<threshold].index

In [96]:
pd.get_dummies(df['Company Names'].replace(repl,'uncommon')).sample(5)

,AUDI,Acura,BMW,Cadillac,Chevrolet,Ford,GMC,Jaguar Land Rover,Kia,LAMBORGHINI,...,Mazda,Mitsubishi,Nissan,Peugeot,Porsche,ROLLS ROYCE,TOYOTA,Tata Motors,Volkswagen,uncommon
318,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
390,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
422,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
123,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
148,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False